spring:
  datasource:
    url: jdbc:mysql://localhost:3306/integral?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  
  #datasource:
  #  url: jdbc:h2:file:~/h2db/sample;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;DATABASE_TO_UPPER=false;INIT=CREATE SCHEMA IF NOT EXISTS public
  #  platform: h2
  #  username: sa
  #  password:
  #  driverClassName: org.h2.Driver
    
  #  schema: 
  #    - classpath:db/schema.sql
  #  data: classpath:db/data.sql 
  #  initialization-mode: never
  #  sql-script-encoding: utf-8
  #  separator: ;
  
  #h2:
  #  console:
  #    enabled: true
  #    path: /console
  #    settings:
  #      trace: false
  #      web-allow-others: false

  # 指定kafka 代理地址，可以多个
  kafka:
    bootstrap-servers: localhost:9092
    producer: 
      retries: 0
      #batch-size=16384
      #buffer-memory=33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: integral-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


ruleengine:
  enabled: true

mybatis: 
  type-aliases-package: com.rsoft.**。model
  mapperLocations: classpath:/mapper/**/*Dao.xml
  
#logging:
#  level:
#    com:
#      rsoft:
#        integral: 
#          dao: debug
  